services:
  frontend:
    build:
      context: ./Front-end
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    container_name: prospect-manager-frontend
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:3001/api

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    container_name: prospect-manager-backend
    volumes:
      - ./Backend/data:/usr/src/app/data
    environment:
      - PORT=3001
      - DATABASE_URL=file:./data/dev.db
      - CORS_ORIGIN=http://localhost:5173

volumes:
  db_data: